### ISSUE TITLE
Consider using an autoloader

### ISSUE THREAD

**Issue by JeffMatson** [iambriansreed/advanced-custom-post-types#3]
An autoloader would be useful here.  Especially when it comes to extending things and as the codebase gets larger.  Issue #2 will help quite a bit with doing this.

**Comment by iambriansreed** [comment]
When I get to a class that won't need to load conditionally definitely. Good suggestions. Leaving this open to remind myself of this until I get out of beta.

**Comment by JeffMatson** [comment]
Conditionally loading classes doesn't matter.  The autoloader will only pull the file if it is specifically called.

**Comment by iambriansreed** [comment]
Learned a chunk about autoloaders, thanks for the suggestion when I have more than one or two classes I will add an autoloader.
